version: "3.9"
services:
  webdiff:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      LANG: ja_JP.UTF-8
      LANGUAGE: ja_JP:ja
      LC_ALL: ja_JP.UTF-8
      TZ: JST-9
      TERM: xterm
    volumes:
      - ./src/:/home/